import { z } from "zod";

// Canonical, language-agnostic classifications used for UI coloring/i18n. Free-text fields
// (categories, topics, keywords, emotion, recommended_department, recommended_priority, summary)
// are generated by the LLM in the respondent's/organization's language (Spanish for this
// deployment) and are stored verbatim.
export const ZResponseAnalysisSentiment = z.enum(["positive", "neutral", "negative"]);
export type TResponseAnalysisSentiment = z.infer<typeof ZResponseAnalysisSentiment>;

export const ZResponseAnalysisSeverity = z.enum(["low", "medium", "high"]);
export type TResponseAnalysisSeverity = z.infer<typeof ZResponseAnalysisSeverity>;

export const ZResponseAnalysisCustomerEffort = z.enum(["low", "medium", "high"]);
export type TResponseAnalysisCustomerEffort = z.infer<typeof ZResponseAnalysisCustomerEffort>;

// Structured output contract for the LLM (matches the field names the model is instructed to
// return). Kept in snake_case so the persisted `data` JSON blob mirrors the LLM response 1:1.
export const ZResponseAnalysisPayload = z.object({
  sentiment: ZResponseAnalysisSentiment,
  sentiment_score: z.number().min(-1).max(1),
  severity: ZResponseAnalysisSeverity,
  confidence: z.number().min(0).max(1),
  categories: z.array(z.string()),
  topics: z.array(z.string()),
  keywords: z.array(z.string()),
  emotion: z.string(),
  customer_effort: ZResponseAnalysisCustomerEffort,
  requires_followup: z.boolean(),
  recommended_department: z.string(),
  recommended_priority: z.string(),
  summary: z.string(),
});
export type TResponseAnalysisPayload = z.infer<typeof ZResponseAnalysisPayload>;

// Typed, camelCase representation of the ResponseAnalysis scalar columns (everything except the
// id/responseId/timestamps envelope and the raw `data` JSON blob). Used both to build the
// Prisma write and to expose the analysis on TResponse for the UI. Mirrors
// TResponseAnalysisPayload field-for-field.
export const ZResponseAnalysis = z.object({
  sentiment: ZResponseAnalysisSentiment,
  sentimentScore: z.number(),
  severity: ZResponseAnalysisSeverity,
  confidence: z.number(),
  categories: z.array(z.string()),
  topics: z.array(z.string()),
  keywords: z.array(z.string()),
  emotion: z.string(),
  customerEffort: ZResponseAnalysisCustomerEffort,
  requiresFollowup: z.boolean(),
  recommendedDepartment: z.string(),
  recommendedPriority: z.string(),
  summary: z.string(),
});
export type TResponseAnalysis = z.infer<typeof ZResponseAnalysis>;

/**
 * Maps the LLM's snake_case structured output onto the camelCase columns persisted on
 * ResponseAnalysis (the full payload is stored separately, verbatim, in the `data` JSON column).
 */
export const toResponseAnalysisColumns = (payload: TResponseAnalysisPayload): TResponseAnalysis => ({
  sentiment: payload.sentiment,
  sentimentScore: payload.sentiment_score,
  severity: payload.severity,
  confidence: payload.confidence,
  categories: payload.categories,
  topics: payload.topics,
  keywords: payload.keywords,
  emotion: payload.emotion,
  customerEffort: payload.customer_effort,
  requiresFollowup: payload.requires_followup,
  recommendedDepartment: payload.recommended_department,
  recommendedPriority: payload.recommended_priority,
  summary: payload.summary,
});
